### PR TITLE
filter out equipped items from recycling list

### PR DESCRIPTION
**Pull request by jpw1991**
This filters out equipped items from the recycling list to fix issues:

https://github.com/Ivaylo-Lafchiev/ValheimRecycle/issues/11

https://github.com/Ivaylo-Lafchiev/ValheimRecycle/issues/9

### CODE REVIEW

**Comment by Ivaylo-Lafchiev** [comment]
Currently on vacation, will test this and merge/release sometime next week if all good.

**Comment by jpw1991** [comment]
After feedback from Roger Windberg, I added a patch on `Humanoid.EquipItem` and `Humanoid.UnequipItem` that refreshes the recycling list so with the panel open, while equipping/unequipping items, it is dynamically reflected in the list.

**Review by rogerwindberg — APPROVED** [review]
LGTM! :)

**Review by Ivaylo-Lafchiev — APPROVED** [review]

**Comment by Ivaylo-Lafchiev** [comment]
Thanks for this. Released this as 2.5.0 and added you as a contributor on the Mod page - https://www.nexusmods.com/valheim/mods/425?tab=description.

**Comment by jpw1991** [comment]
You're welcome :) Thanks for listing me as a contributor

**Pull request merged**
